Identitiy/Controllers/FemaleController.cs
using Identitiy.MyContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Identitiy.Controllers
{
    [Authorize(Policy ="FemalePolicy")]
    public class FemaleController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        public FemaleController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> AddCalimAsync(int id)
        {
            
            var user = _userManager.Users.FirstOrDefault(x => x.Id==id);
            if((await _userManager.GetClaimsAsync(user)).Count == 0)
            {
                Claim claim = new Claim("gender", "female");
                await _userManager.AddClaimAsync(user, claim);
            }
           

            return RedirectToAction("USerList","Rol");
        }
    }
}

Identitiy/Controllers/RolController.cs
using Identitiy.Models;
using Identitiy.MyContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Identitiy.Controllers
{
    [Authorize]
    public class RolController : Controller
    {
        private readonly RoleManager<AppRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;
        public RolController(RoleManager<AppRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }
        public IActionResult AddRole()
        {
            return View(new RoleViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> AddRoleAsync(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppRole role = new AppRole
                {
                    Name = model.Name
                };
                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);
        }
        [Authorize(Roles ="Admin")]
        public IActionResult UserList()
        {
            return View(_userManager.Users.ToList());
        }
        public async Task<IActionResult> AssignRoleAsync(int id)
        {
            var user =_userManager.Users.FirstOrDefault(x => x.Id == id);
            TempData["UserId"] = user.Id;
            var roles = _roleManager.Roles.ToList();
            var userRoles =  await _userManager.GetRolesAsync(user);
            List<RoleAssignViewModel> models = new List<RoleAssignViewModel>();
            foreach (var item in roles)
            {
                RoleAssignViewModel model = new RoleAssignViewModel();
                model.RoleId = item.Id;
                model.Name = item.Name;
                model.Exists = userRoles.Contains(item.Name);
                models.Add(model);
            }
            return View(models);

        }
        [HttpPost]
        public async Task<IActionResult> AssignRoleAsync(List<RoleAssignViewModel> models)
        {
            var userId = (int)(TempData["UserId"]);
            var user = _userManager.Users.FirstOrDefault(x => x.Id == userId);
            foreach (var item in models)
            {
                if (item.Exists)
                {
                   await _userManager.AddToRoleAsync(user, item.Name);

                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, item.Name);
                }
            }
            return RedirectToAction("UserList");
        }

    }
}

Identitiy/Views/Rol/AddRole.cshtml
@model RoleViewModel
@{
    ViewData["Title"] = "AddRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="AddRole" method="post" class="w-75 mx-auto p-3">
    <div class="form-group">
        <label asp-for="Name"></label>
        <span asp-validation-for="Name"></span>
        <input asp-for="Name" class="form-control"> 
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="submit" class="btn btn-info" value="Kaydet" />
</form>

Identitiy/Views/Rol/AssignRole.cshtml
@model List<RoleAssignViewModel>
@{
    ViewData["Title"] = "AssignRoleAsync";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="AssignRole" method="post" class="w-75 p-3 mx-auto">
    @for(int i =0;i<Model.Count;i++){
        <div class="form-check">
            <input type="hidden" asp-for="@Model[i].RoleId"/>
            <input type="hidden" asp-for="@Model[i].Name"/>
            <input type="checkbox" class="form-check-input" asp-for="@Model[i].Exists"/>
            <label  class="form-check-label" for="@Model[i].Exists">@Model[i].Name</label>
            
        </div>

    }
    <input type="submit" value="Kaydet" class="btn btn-info"/>
</form>

Identitiy/Views/Rol/Index.cshtml
@model List<AppRole>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a asp-action="AddRole" asp-controller="Rol" class ="btn btn-info btn-sm my-2" >Yeni Rol Ekle</a>
<table class="table table-sm table-hover">
    <tr>
        <td>AD</td>
        <td>Rol güncelle (klasik veritabanı değer güncelleme )</td>
        <td>Rol sil (klasik veritabanı değer silme. )</td>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
        </tr>
    }

</table>

Identitiy/Views/Rol/UserList.cshtml
@model List<AppUser>

@{
    ViewData["Title"] = "UserList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="table table-sm table-hover">
    <tr>
        <td>AD</td>
        <td>Roller</td>
        <td>Claim</td>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td><a asp-action="AssignRole" asp-route-id ="@item.Id" class=
        "btn btn-warning btn-sm">Rol Ata</a></td>
        <td>
            <a asp-action="AddClaim" asp-controller="Female" asp-route-id="@item.Id" class="btn btn-info btn-sm">Claim Ekle</a>
        </td>
        </tr>
    }

</table>