Identitiy/Controllers/PanelController.cs
using Identitiy.Models;
using Identitiy.MyContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Identitiy.Controllers
{
    [Authorize]
    public class PanelController : Controller
    {
     private readonly UserManager<AppUser> _userManager;
     private readonly SignInManager<AppUser> _signInManager;
        public PanelController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(user);
        }
        public async Task<IActionResult> UpdateUser()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            UserUpdateViewModel model = new UserUpdateViewModel
            {
                Email=user.Email,
                Name=user.Name,
                SurName=user.SurName,
                PhoneNumber=user.PhoneNumber,
                PictureUrl=user.PictureUrl,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserUpdateViewModel model)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (model.Picture != null)
            {
                var uygYer = Directory.GetCurrentDirectory();
                var uzanti = Path.GetExtension(model.Picture.FileName); //Name sadece adı filename uzantıyla beraber
                var resimAd = Guid.NewGuid() + uzanti;
                var kayıtYer = uygYer + "/wwwroot/img/" + resimAd;
              
                using var stream = new FileStream(kayıtYer,FileMode.Create);
                await model.Picture.CopyToAsync(stream);
                user.PictureUrl = resimAd;
            }
            user.Name = model.Name;
            user.SurName = model.SurName;
            user.Email = model.Email;
            user.PhoneNumber = model.PhoneNumber;
            var Result = await _userManager.UpdateAsync(user);

            if (Result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var item in Result.Errors)
            {
                ModelState.AddModelError("", item.Description);
            }
      
            return View(model);
        }
        public async Task<IActionResult> LogOutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Identitiy/Views/Panel/Index.cshtml
@model AppUser
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

<div class="row">
<div class="col-md-8">
    <table class="table table-hover table sm">
    <tr>
        <th>İsim:</th>
        <td>@Model.Name</td>
    </tr>
     <tr>
        <th>Soyisim:</th>
        <td>@Model.SurName</td>
    </tr>
     <tr>
        <th>Email:</th>
        <td>@Model.Email</td>
    </tr>
     
</table>
</div>
<div class="col-md-4">
    <img src="~/img/@Model.PictureUrl" alt="@Model.Name" class="w-100 img-fluid img-thumbnail" />

</div>
    
</div>

Identitiy/Views/Panel/UpdateUser.cshtml
@model UserUpdateViewModel

@{
    ViewData["Title"] = "UpdateUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
<form asp-action="UpdateUser" asp-controller="Panel" method="post"
class="w-75 mx-auto p-3" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <span asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" />
    </div>
    <br /> <div class="form-group">
        <label asp-for="SurName"></label>
        <span asp-validation-for="SurName" class="text-danger"></span>
        <input asp-for="SurName" />
    </div>
    <br />
    <div class="form-group">
        <label asp-for="Email"></label>
        <span asp-validation-for="Email" class="text-danger"></span>
        <input asp-for="Email" />
    </div>
    <br />
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        <input asp-for="PhoneNumber" />
    </div>
    <br />
    <div class="form-group">
        <div class="row">
            <div class="col-md-4">
                <label>Bir Önceki Resminiz.</label>
                <img src="~/img/@Model.PictureUrl" alt="@Model.Name" style="height:4rem!important;width:5rem!important" />
            </div>
            <div class="col-md-8">
                <input type="file" asp-for="@Model.Picture"/>
            </div>
            
        </div>
    </div>
    <div asp-validation-summary="ModelOnly" class ="text-danger">
        
    </div>
    <button class="btn btn-info" type="submit">Kaydet</button>
</form>